"""empty message

Revision ID: 1e3cb286d242
Revises: 4eb06cd41409
Create Date: 2020-08-13 16:02:56.363439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e3cb286d242'
down_revision = '4eb06cd41409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotel', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotel', 'description')
    # ### end Alembic commands ###
