"""empty message

Revision ID: 20288fc8e506
Revises: 512e6a55aabb
Create Date: 2020-08-11 23:17:11.225569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20288fc8e506'
down_revision = '512e6a55aabb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('available', sa.String(), nullable=True),
    sa.Column('driver', sa.String(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
